# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slice_sample_normal_ex <- function(y_data, x_data, mean_x_preds, beta, sigma_2_y, sigma_x_preds, LOD_lower, LOD_upper, sample_size) {
    .Call(`_lodr_slice_sample_normal_ex`, y_data, x_data, mean_x_preds, beta, sigma_2_y, sigma_x_preds, LOD_lower, LOD_upper, sample_size)
}

LOD_fit_test <- function(y_data, x_data, mean_x_preds, beta, sigma_2_y, sigma_x_preds, no_of_samples, threshold, max_iterations, LOD_u_l, ystart) {
    .Call(`_lodr_LOD_fit_test`, y_data, x_data, mean_x_preds, beta, sigma_2_y, sigma_x_preds, no_of_samples, threshold, max_iterations, LOD_u_l, ystart)
}

bootstrap_test <- function(num_of_boots, y_data, x_data, no_of_samples, threshold, max_iterations, LOD_u_l, ystart) {
    .Call(`_lodr_bootstrap_test`, num_of_boots, y_data, x_data, no_of_samples, threshold, max_iterations, LOD_u_l, ystart)
}

LOD_fit_multiple <- function(y_data, x_data, mean_x_preds, beta, sigma_2_y, sigma_x_preds, no_of_samples, threshold, max_iterations, LOD_u_l, sampler) {
    .Call(`_lodr_LOD_fit_multiple`, y_data, x_data, mean_x_preds, beta, sigma_2_y, sigma_x_preds, no_of_samples, threshold, max_iterations, LOD_u_l, sampler)
}

bootstrap_multi_test <- function(num_of_boots, y_data, x_data, no_of_samples, threshold, max_iterations, LOD_u_l, sampler) {
    .Call(`_lodr_bootstrap_multi_test`, num_of_boots, y_data, x_data, no_of_samples, threshold, max_iterations, LOD_u_l, sampler)
}

